- EffGasDayTime
- PipelineName
- CycleDesc
- LocPurpDesc
- Loc
- LocName
- LocZn
- LocSegment
- DesignCapacity
- OperatingCapacity
- TotalScheduledQuantity
- OperationallyAvailableCapacity
- IT
- FlowInd
- AllQtyAvail
- QtyReason
- Timestamp
- GFLOC
