"AG": 6951446
"BGS": 614834559
"BIG": "BIG Pipeline"
"BSP": 968195714
"EG": "MHP Egan"
"ET": 7921323
"GB": "Garden Banks"
"GPL": 36638044
"MCGP": 962767138
"MB": "MHP Moss Bluff"
"MNCA": "Maritimes & Northeast Canada"
"MNUS": "Maritimes & Northeast U.S."
"MR": "Manta Ray Offshore Gathering Company"
"NPC": "Nautilus Pipeline Company"
"NXCA": "NEXUS ULC"
"NXUS": "NEXUS U.S."
"SESH": "Southeast Supply Header"
"SG": "Saltville"
"SR": "Steckman Ridge"
"STT": "Sabal Trail"
"TE": "Texas Eastern"
"TPGS": "Tres Palacios Gas Storage LLC"
"VCP": "Valley Crossing Pipeline"
"WE": "Westcoast Energy"
"WRGS": "Walker Ridge Gathering System"
