OA:
  - AG
  - BGS
  - BSP
  - EG
  - ET
  - GB
  - GPL
  - MCGP
  - MNUS
  - NPC
  - NXUS
  - SESH
  - SG
  - SR
  - STT
  - TE
  - TPGS
  - VCP

OC:
  - AG
  - BGS
  - BSP
  - EG
  - ET
  - GB
  - MCGP
  - MNUS
  - NPC
  - NXUS
  - SESH
  - SG
  - SR
  - STT
  - TE
  - TPGS

SC:
  - BGS
  - EG
  - ET
  - SG
  - SR
  - TE
  - TPGS
